### PR TITLE
Initial version of Tech Stacks Divide & Conquer

### PR DESCRIPTION
**Pull request by Hamled**
This is missing most of the specific technologies to be included for
each of the four tech stacks.

### CODE REVIEW

**Comment by kariabancroft** [comment]
Looks good - I think I might want to add a note about how we will do the research, get back with the group and then present the findings for each piece and the tech stack as a whole? Might also be worthwhile to mention that we'll put all of the info that we learn into a doc. Or we could just say that to the students in person.

**Comment by CheezItMan** [comment]
Maybe we could setup Google Slides with each group getting 3 slides, one for each aspect of the tech stack they are investigating, and then by the end we'll have a document filled with the findings from each group shared among them.  

It would also make presenting easier.

**Comment by kariabancroft** [comment]
@CheezItMan Yeah - that seems like a nice idea! I don't know about everyone editing the doc all at once, but then at least it would be less work to have everything all in one place

**Comment by CheezItMan** [comment]
@kariabancroft as long as each group is working on different individual slides it can work pretty well.  I've done it before with larger classes.

**Review by CheezItMan — APPROVED** [review]
Looks good so far.  I can help build the list of techs in a Google Slideshow if needed.

**Comment by Hamled** [comment]
@CheezItMan Sounds good, I don't know anything about Google Slides.

**Comment by Hamled** [comment]
@CheezItMan The tech stack details are filled out now, you should be able to work on the Google Slides stuff.

@kariabancroft I updated the presentation instructions to speak to what you mentioned.

**Pull request merged**
